### ISSUE TITLE
Enhance [StringResult]: provide a more convenient way to create JSON responses

### ISSUE THREAD

**Issue by benjaminknauer** [creios/creiwork-framework#19]
- Add static function `createEncodedJsonResult(array $props): StringResult` (and counterpart for  `createXmlResult`) that creates an correctly formated `StringResult` from an Array.

- `createJsonResult(json_encode(array('example' => 'exampleText')))`
shold resturn the same `StringResult` as
`createEncodedJsonResult(array('example' => 'exampleText'))`

- Naming alternative: `createJsonResultFromArray`

**Comment by MazeChaZer** [comment]
We could leave the `StringResult` as is and rename the `SerializableResult` to `JsonResult` to handle the encoding of JSON data.

**Comment by timtegeler** [comment]
@MazeChaZer This is a good idea. 

I would like to one step further. I my opinion the serialization to xml, plain and html is overkill and no use case for us. Let us drop the whole support for content negotiation and only serialize to json.

@benjaminknauer what do you think?

**Comment by timtegeler** [comment]
This could resolve implicit #17
