### ISSUE TITLE
Provide ResponseFactory for Usage in Middlewares and PostProcessor (internally)

### ISSUE THREAD

**Issue by benjaminknauer** [creios/creiwork-framework#21]
We could create a ResponseFactory which provides a couple of convenient methods to create Responses. This could be used inside Middlewares as well as internally inside the PostProcessor.

This is the way you would create a JSON Response inside a Middleware atm:
```
$bodyArray = ['error' => 'invalid credentials'];
$response = Factory::createResponse(401)->withBody(stream_for(json_encode($bodyArray)))
->withHeader('Content-Type', 'application/json');
```

I would like something like that:
```
$bodyArray = ['error' => 'invalid credentials'];
$response = ResponseFactory::createJsonResponse(401, $bodyArray);
```

**Comment by MazeChaZer** [comment]
We talked about this today and came to the conclusion that the `PostProcessor` class already acts as a response factory. Maybe just rename the class to make the purpose more clear?
We can talk about this in detail tomorrow, @timtegeler
