### ISSUE TITLE
Add standard DI config for JMSSerializer

### ISSUE THREAD

**Issue by benjaminknauer** [creios/creiwork-framework#22]
Figure out a good standard configuration which is suitable for most project.
* use camelCase not snake-case
* throw exception if types do not match
* is it possible to set values to required?
* maybe configure it in order to use annotations out of the box
@MazeChaZer @timtegeler

**Comment by MazeChaZer** [comment]
Possible alternative to the JMS serializer: https://github.com/suin/php-marshaller
